.PHONY: clean All

All:
	@echo "----------Building project:[ keyb_alt_ctrl - Debug ]----------"
	@cd "keyb_alt_ctrl" && "$(MAKE)" -f  "keyb_alt_ctrl.mk" && "$(MAKE)" -f  "keyb_alt_ctrl.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ keyb_alt_ctrl - Debug ]----------"
	@cd "keyb_alt_ctrl" && "$(MAKE)" -f  "keyb_alt_ctrl.mk" clean
