.PHONY: clean All

All:
	@echo "----------Building project:[ fibonacci - Debug ]----------"
	@cd "fibonacci" && "$(MAKE)" -f  "fibonacci.mk" && "$(MAKE)" -f  "fibonacci.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ fibonacci - Debug ]----------"
	@cd "fibonacci" && "$(MAKE)" -f  "fibonacci.mk" clean
