.PHONY: clean All

All:
	@echo "----------Building project:[ goldbach_conjecture - Debug ]----------"
	@cd "goldbach_conjecture" && "$(MAKE)" -f  "goldbach_conjecture.mk"
clean:
	@echo "----------Cleaning project:[ goldbach_conjecture - Debug ]----------"
	@cd "goldbach_conjecture" && "$(MAKE)" -f  "goldbach_conjecture.mk" clean
