.PHONY: clean All

All:
	@echo "----------Building project:[ uppg5_4-9 - Debug ]----------"
	@cd "uppg5_4" && "$(MAKE)" -f  "uppg5_4-9.mk" && "$(MAKE)" -f  "uppg5_4-9.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ uppg5_4-9 - Debug ]----------"
	@cd "uppg5_4" && "$(MAKE)" -f  "uppg5_4-9.mk" clean
