.PHONY: clean All

All:
	@echo "----------Building project:[ uppg5_17 - Debug ]----------"
	@cd "uppg5_17" && "$(MAKE)" -f  "uppg5_17.mk" && "$(MAKE)" -f  "uppg5_17.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ uppg5_17 - Debug ]----------"
	@cd "uppg5_17" && "$(MAKE)" -f  "uppg5_17.mk" clean
